#!/bin/bash

cp vimrc ~/.vimrc
cp iceberg.vim ~/.vim/colors/iceberg.vim
cp neobundle.vim ~/.vim/neobundle.vim
cp zpreztorc ~/.zpreztorc
cp zshrc ~/.zshrc
cp prompt_garrett_setup ~/.zprezto/modules/prompt/functions/prompt_garrett_setup
cp gitignore_global ~/.gitignore
cp gitconfig_global ~/.gitconfig
