#!/bin/bash

FILES=(
  ~/.vimrc
  ~/.vim/colors/iceberg.vim
  ~/.vim/neobundle.vim
  ~/.zpreztorc
  ~/.zshrc
  ~/.zprezto/modules/prompt/functions/prompt_garrett_setup
  ~/.gitignore_global
  ~/.gitconfig
)

mkdir -p local-backup                                     # make backup folder

for i in "${FILES[@]}"                                    # loop through files
do
  if [ -e $i ]; then
    cp -LRH $i local-backup/"$(echo $i | sed 's/.*\///')" # backup locally just in case
    rm $i                                                 # remove to make room for link
  fi
  ln -s $(pwd)/"$(echo $i | sed 's/.*\///')" $i           # symlink to this repo
done
